"""empty message

Revision ID: 1fa84352c56c
Revises: 
Create Date: 2024-11-12 19:30:00.039806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa84352c56c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('Quarto',
    sa.Column('nro', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('nro')
    )
    op.create_table('Status',
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('Data',
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('nro_quarto', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['nro_quarto'], ['Quarto.nro'], ),
    sa.PrimaryKeyConstraint('data', 'nro_quarto')
    )
    op.create_table('Reserva',
    sa.Column('nro', sa.Integer(), nullable=False),
    sa.Column('nome_status', sa.String(length=50), nullable=True),
    sa.Column('data_inicio_data', sa.Date(), nullable=False),
    sa.Column('numero_quarto_data_inicio', sa.Integer(), nullable=False),
    sa.Column('data_fim_data', sa.Date(), nullable=False),
    sa.Column('nro_quarto_data_fim', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_fim_data', 'nro_quarto_data_fim'], ['Data.data', 'Data.nro_quarto'], ),
    sa.ForeignKeyConstraint(['data_inicio_data', 'numero_quarto_data_inicio'], ['Data.data', 'Data.nro_quarto'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['Cliente.id'], ),
    sa.ForeignKeyConstraint(['nome_status'], ['Status.nome'], ),
    sa.PrimaryKeyConstraint('nro')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reserva')
    op.drop_table('Data')
    op.drop_table('Status')
    op.drop_table('Quarto')
    op.drop_table('Cliente')
    # ### end Alembic commands ###
